#!/usr/bin/python3
""" RSA Laboratories states that: for 
each RSA number n, there exist prime
numbers p and q such that
n = p * q
"""
from sys import argv
def rsa(value):
    i = 2
    if (value < 2):
        return
    while value % i:
        i += 2
        print("{:.0f} = {:.0f} * {:.0f}".format(value, value // i, i))
if len(argv) != 2:
    exit()
try:
    with open(argv[1]) as file:
        line = file.readline()
        while line != "":
            value = int(line.split('\n'[0]))
            rsa(value)
            line = file.readline()
except:
    pass
