#!/usr/bin/python3
""" Factorize as many numbers as possible into a product of two smaller numbers."""
import sys

def factorial():
    """defines a function called factorial"""

    try:
        temp = sys.argv[1]
        with open(temp) as file_object:
            for i in file_object:
                i = int(i)
                if i % 2 == 0:
                    print("{} = {} * {}".format(i, 2, i // 2))
                    continue
                n = 3
                div = i // 2
                while n < div:
                    if i % n == 0:
                        print("{} = {} * {}".format(i, n, i // n))
                        break
                    n = n + 2
                if n == div + 1:
                    print("{}={}*{}".format(i, i, 1))
    except(IndexError):
        pass
factorial()
